name = "HTM"
uuid = "5fe4914d-c46a-425a-8229-6c1f1b390250"
authors = ["Felipe S. S. Schneider <schneider.felipe@posgrad.ufsc.br> and contributors"]
version = "0.1.0"

[deps]
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"

[compat]
Hyperscript = "0.0.4"
julia = "1.4"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
